import React from "react";
import "./aeo.css";

// ===========================================================================
// AIPUSH AEO Analyzer — production React page wired to /api/aeo/*.
// Single-page flow: landing -> scanning -> results, with a server-side email
// gate. Faithful to the claude.ai/design prototype (Catppuccin tokens, gold
// accent, semicircle gauge), scoped under .aeo-root so it cannot collide with
// the rest of the site's styles.
// ===========================================================================

const { useState, useEffect, useRef, useCallback, useMemo } = React;

type Status = "pass" | "fail" | "skip" | "info";

interface Doc {
  t: string;
  u: string;
}

interface ApiFinding {
  id: string;
  title: string;
  category: string;
  categoryLabel: string;
  severity: string;
  status: Status;
  goal?: string;
  why?: string;
  issue?: string;
  fix?: string;
  techDetail?: string;
  skillSlug?: string;
  skillUrl?: string;
  docs?: string[];
  scoring?: boolean;
  locked?: boolean;
}

interface ApiCategory {
  id: string;
  label: string;
  score: number;
  passed: number;
  total: number;
}

interface ScanResponse {
  scanId: string;
  url: string;
  host: string;
  score: number;
  level: number;
  levelLabel: string;
  categories: ApiCategory[];
  findings: ApiFinding[];
  lockedCount?: number;
  locked?: boolean;
  scannedAt?: string;
}

const SCAN_PHASES = [
  "Fetching homepage…",
  "Reading robots.txt…",
  "Probing /.well-known…",
  "Inspecting response headers…",
  "Negotiating Markdown…",
  "Checking structured data…",
  "Scoring agent-readiness…",
];

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// ---- theme ----------------------------------------------------------------

function initialTheme(): "light" | "dark" {
  try {
    const s = localStorage.getItem("aeo-theme");
    if (s === "light" || s === "dark") return s;
  } catch {
    /* ignore */
  }
  if (typeof window !== "undefined" && window.matchMedia) {
    return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  }
  return "light";
}

// ---- helpers --------------------------------------------------------------

function docLabel(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

/** Build the copy-ready markdown instruction for one finding (mirrors the
 *  server's renderFindingMarkdown so the per-card "Copy" matches the bundle). */
function findingMarkdown(f: ApiFinding, targetUrl: string): string {
  const lines: string[] = [];
  lines.push(`## ${f.title}`);
  lines.push("");
  if (f.goal) lines.push(`**Goal:** ${f.goal}`);
  if (f.why) lines.push(`**Why it matters:** ${f.why}`);
  if (f.issue) lines.push(`**Issue:** ${f.issue}`);
  if (f.fix) lines.push(`**Fix:** ${f.fix}`);
  if (f.techDetail) {
    lines.push("");
    lines.push("```");
    lines.push(f.techDetail);
    lines.push("```");
  }
  lines.push("");
  lines.push(`Target site: ${targetUrl}`);
  if (f.skillUrl) lines.push(`Skill: ${f.skillUrl}`);
  if (f.docs && f.docs.length) lines.push(`Docs: ${f.docs.join(", ")}`);
  return lines.join("\n");
}

function bundleMarkdown(data: ScanResponse): string {
  const actionable = data.findings.filter((f) => f.status === "fail" && !f.locked);
  const out: string[] = [];
  out.push(`# AEO fixes for ${data.url}`);
  out.push("");
  out.push(`Score: ${data.score}/100 — AEO Level ${data.level} (${data.levelLabel})`);
  out.push("");
  for (const f of actionable) {
    out.push(findingMarkdown(f, data.url));
    out.push("");
    out.push("---");
    out.push("");
  }
  out.push("Generated by AIPUSH — https://aipush.app");
  return out.join("\n");
}

// ---- API ------------------------------------------------------------------

async function apiScan(url: string): Promise<ScanResponse> {
  const r = await fetch("/api/aeo/scan", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
    body: JSON.stringify({ url }),
  });
  const j = await r.json().catch(() => null);
  if (!r.ok) throw new Error(j?.error || "SCAN_FAILED");
  return j as ScanResponse;
}

async function apiGetScan(scanId: string, full: boolean): Promise<ScanResponse | null> {
  const path = full ? `/api/aeo/scan/${scanId}/full` : `/api/aeo/scan/${scanId}`;
  const r = await fetch(path, { credentials: "include" });
  if (!r.ok) return null;
  return (await r.json().catch(() => null)) as ScanResponse | null;
}

async function apiSubscribe(email: string, scanId: string): Promise<boolean> {
  const r = await fetch("/api/aeo/subscribe", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
    body: JSON.stringify({ email, consent: true, scanId }),
  });
  return r.ok;
}

// ---- components -----------------------------------------------------------

function CopyBtn({ text, label = "Copy", cls = "copy-btn" }: { text: string; label?: string; cls?: string }) {
  const [done, setDone] = useState(false);
  return (
    <button
      className={cls}
      type="button"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
        } catch {
          /* ignore */
        }
        setDone(true);
        setTimeout(() => setDone(false), 1400);
      }}
    >
      {done ? "Copied ✓" : label}
    </button>
  );
}

function Gauge({ score, levelLabel, level, style }: { score: number; levelLabel: string; level: number; style: string }) {
  const pct = Math.max(0, Math.min(100, score)) / 100;
  const color = score >= 70 ? "var(--green)" : score >= 40 ? "var(--gold)" : "var(--red)";
  if (style === "ring") {
    const r = 80;
    const c = 2 * Math.PI * r;
    const dash = `${c * pct} ${c}`;
    return (
      <div className="gauge-wrap">
        <svg viewBox="0 0 200 200" className="gauge gauge-ring" role="img" aria-label={`Score ${score} of 100`}>
          <circle cx="100" cy="100" r="80" fill="none" stroke="var(--surface0)" strokeWidth="14" />
          <circle
            cx="100"
            cy="100"
            r="80"
            fill="none"
            stroke={color}
            strokeWidth="14"
            strokeLinecap="round"
            strokeDasharray={dash}
            transform="rotate(-90 100 100)"
            style={{ transition: "stroke-dasharray 1s ease" }}
          />
        </svg>
        <div className="gauge-num">
          <span className="gnum">{score}</span>
          <span className="gmax">/100</span>
        </div>
        <div className="gauge-level">Level {level} · {levelLabel}</div>
      </div>
    );
  }
  if (style === "dashed") {
    const seg = 40;
    const r = 80;
    const on = Math.round(seg * pct);
    return (
      <div className="gauge-wrap">
        <svg viewBox="0 0 200 120" className="gauge" role="img" aria-label={`Score ${score} of 100`}>
          {Array.from({ length: seg }).map((_, i) => {
            const a = (Math.PI * (i + 0.5)) / seg;
            const x = 100 - Math.cos(a) * r;
            const y = 100 - Math.sin(a) * r;
            return <circle key={i} cx={x} cy={y} r="3.2" fill={i < on ? color : "var(--surface0)"} />;
          })}
        </svg>
        <div className="gauge-num">
          <span className="gnum">{score}</span>
          <span className="gmax">/100</span>
        </div>
        <div className="gauge-level">Level {level} · {levelLabel}</div>
      </div>
    );
  }
  // semicircle (default)
  const r = 80;
  const c = Math.PI * r;
  const dash = `${c * pct} ${c}`;
  return (
    <div className="gauge-wrap">
      <svg viewBox="0 0 200 120" className="gauge" role="img" aria-label={`Score ${score} of 100`}>
        <path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--surface0)" strokeWidth="14" strokeLinecap="round" />
        <path
          d="M20 100 A80 80 0 0 1 180 100"
          fill="none"
          stroke={color}
          strokeWidth="14"
          strokeLinecap="round"
          strokeDasharray={dash}
          style={{ transition: "stroke-dasharray 1s ease" }}
        />
      </svg>
      <div className="gauge-num">
        <span className="gnum">{score}</span>
        <span className="gmax">/100</span>
      </div>
      <div className="gauge-level">Level {level} · {levelLabel}</div>
    </div>
  );
}

function FixCard({ finding, url, density }: { finding: ApiFinding; url: string; density: string }) {
  const [open, setOpen] = useState(false);
  const st = finding.status;
  const icon = st === "pass" ? "✓" : st === "fail" ? "✕" : "•";
  const docs: Doc[] = (finding.docs || []).map((u) => ({ t: docLabel(u), u }));
  return (
    <div className={`fix-card ${st} ${open ? "open" : ""} ${density}`}>
      <button className="fix-head" type="button" aria-expanded={open} onClick={() => setOpen((o) => !o)}>
        <span className={`fix-icon ${st}`}>{icon}</span>
        <span className="fix-title">{finding.title}</span>
        <span className="fix-status">{st}</span>
        <span className="fix-chev">{open ? "▲" : "▼"}</span>
      </button>
      {open && (
        <div className="fix-body">
          {finding.goal && (
            <div className="fix-line">
              <b>Goal</b>
              <span>{finding.goal}</span>
            </div>
          )}
          {finding.issue && (
            <div className="fix-line">
              <b>Issue</b>
              <span>{finding.issue}</span>
            </div>
          )}
          {finding.fix && (
            <div className="fix-line">
              <b>How</b>
              <span>{finding.fix}</span>
            </div>
          )}
          {docs.length > 0 && (
            <div className="fix-res">
              {docs.map((d, i) => (
                <a key={i} href={d.u} target="_blank" rel="noopener noreferrer">
                  {d.t} ↗
                </a>
              ))}
              {finding.skillUrl && (
                <a href={finding.skillUrl} target="_blank" rel="noopener noreferrer">
                  Skill ↗
                </a>
              )}
            </div>
          )}
          {finding.status === "fail" && (
            <div className="fix-actions">
              <CopyBtn text={findingMarkdown(finding, url)} label="Copy fix for agent" />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Gate({ locked, scanId, onSent }: { locked: number; scanId: string; onSent: () => void }) {
  const [email, setEmail] = useState("");
  const [agree, setAgree] = useState(false);
  const [sent, setSent] = useState(false);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const ok = EMAIL_RE.test(email) && agree;

  if (sent) {
    return (
      <div className="gate gate-sent">
        <div className="gate-icon">✉</div>
        <h3>Check your inbox</h3>
        <p>
          We sent a confirmation link to <b>{email}</b>. Click it to unlock all {locked} fixes.
        </p>
      </div>
    );
  }

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!ok || busy) return;
    setBusy(true);
    setErr("");
    const success = await apiSubscribe(email.trim().toLowerCase(), scanId);
    setBusy(false);
    if (success) {
      setSent(true);
      onSent();
    } else {
      setErr("Something went wrong. Please try again.");
    }
  };

  return (
    <div className="gate">
      <div className="gate-lock">🔒</div>
      <h3>Unlock all {locked} fixes</h3>
      <p>Get the full report plus copy-ready fixes for every issue. Free.</p>
      <form onSubmit={submit}>
        <input
          type="email"
          placeholder="you@company.com"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoComplete="email"
        />
        <label className="gate-agree">
          <input type="checkbox" checked={agree} onChange={(e) => setAgree(e.target.checked)} />
          <span>Email me my report and occasional AEO tips. Unsubscribe anytime.</span>
        </label>
        <button className="gate-btn" type="submit" disabled={!ok || busy}>
          {busy ? "Sending…" : "Unlock report →"}
        </button>
        {err && <div className="gate-err">{err}</div>}
        <div className="gate-agree" style={{ justifyContent: "center", opacity: 0.7 }}>
          <span>Double opt-in — confirm via the link we email you.</span>
        </div>
      </form>
    </div>
  );
}

function useTweaks() {
  const [gauge, setGauge] = useState("semicircle");
  const [density, setDensity] = useState("comfy");
  return { gauge, setGauge, density, setDensity };
}

function TweaksPanel({ t }: { t: ReturnType<typeof useTweaks> }) {
  const [open, setOpen] = useState(false);
  if (!open) {
    return (
      <button className="tweaks-fab" type="button" onClick={() => setOpen(true)} aria-label="Open tweaks">
        ⚙
      </button>
    );
  }
  return (
    <div className="tweaks-panel">
      <div className="tweaks-head">
        <span>Tweaks</span>
        <button type="button" onClick={() => setOpen(false)} aria-label="Close">
          ✕
        </button>
      </div>
      <div className="tweaks-row">
        <label>Score gauge</label>
        <div className="seg">
          {["semicircle", "ring", "dashed"].map((g) => (
            <button key={g} type="button" className={t.gauge === g ? "on" : ""} onClick={() => t.setGauge(g)}>
              {g}
            </button>
          ))}
        </div>
      </div>
      <div className="tweaks-row">
        <label>Card density</label>
        <div className="seg">
          {["comfy", "compact"].map((d) => (
            <button key={d} type="button" className={t.density === d ? "on" : ""} onClick={() => t.setDensity(d)}>
              {d}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function Landing({ onAnalyze, error }: { onAnalyze: (url: string) => void; error: string }) {
  const [url, setUrl] = useState("");
  return (
    <div className="hero">
      <div className="hero-badge">✦ AIPUSH · AEO ANALYZER</div>
      <h1>
        Is your site ready
        <br />
        for AI agents?
      </h1>
      <p className="sub">
        Scan your site for AI-agent and answer-engine readiness — robots, sitemaps, MCP, structured data, and more.
      </p>
      <form
        className="url-row"
        onSubmit={(e) => {
          e.preventDefault();
          if (url.trim()) onAnalyze(url.trim());
        }}
      >
        <input
          className="url-input"
          type="text"
          inputMode="url"
          placeholder="https://yourwebsite.com"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          autoFocus
        />
        <button className="analyze-btn" type="submit" disabled={!url.trim()}>
          Analyze →
        </button>
      </form>
      <p className="tiny">Free · No account needed to start</p>
      {error && <p className="err">{error}</p>}
    </div>
  );
}

function Scanning({ url, done }: { url: string; done: boolean }) {
  const [i, setI] = useState(0);
  useEffect(() => {
    // Advance phases on a gentle timer until the real scan resolves; when the
    // request completes (`done`), jump to the final phase.
    if (done) {
      setI(SCAN_PHASES.length);
      return;
    }
    if (i >= SCAN_PHASES.length - 1) return;
    const t = setTimeout(() => setI((n) => n + 1), 900);
    return () => clearTimeout(t);
  }, [i, done]);
  const shown = Math.min(i, SCAN_PHASES.length);
  const pct = Math.min(100, Math.round((100 * shown) / SCAN_PHASES.length));
  return (
    <div className="scanning">
      <div className="scan-url">{url}</div>
      <div className="scan-ring">
        <div className="scan-fill" style={{ width: `${pct}%` }} />
      </div>
      <ul className="scan-phases">
        {SCAN_PHASES.map((p, idx) => (
          <li key={idx} className={idx < shown ? "done" : idx === shown ? "active" : ""}>
            <span className="ph-dot">{idx < shown ? "✓" : "○"}</span>
            {p}
          </li>
        ))}
      </ul>
    </div>
  );
}

function Results({
  data,
  tweaks,
  unlocked,
  onSent,
}: {
  data: ScanResponse;
  tweaks: ReturnType<typeof useTweaks>;
  unlocked: boolean;
  onSent: () => void;
}) {
  // Group findings by category, preserving catalog order within each category.
  const byCat = useMemo(() => {
    const map = new Map<string, ApiFinding[]>();
    for (const f of data.findings) {
      const arr = map.get(f.category) || [];
      arr.push(f);
      map.set(f.category, arr);
    }
    return map;
  }, [data]);

  const lockedCount = data.lockedCount || data.findings.filter((f) => f.locked).length;
  const scoringCats = data.categories;

  let gateRendered = false;

  return (
    <div className="results">
      <div className="result-head">
        <span className="result-url">{data.url}</span>
        <button className="rescan" type="button" onClick={() => location.assign("/")}>
          Scan another ↻
        </button>
      </div>

      <Gauge score={data.score} levelLabel={data.levelLabel} level={data.level} style={tweaks.gauge} />

      <div className="cat-strip">
        {scoringCats.map((c) => (
          <a key={c.id} className="cat-chip" href={`#cat-${c.id}`}>
            <span className="cat-score">{c.score}</span>
            <span className="cat-label">{c.label}</span>
          </a>
        ))}
      </div>

      <div className="cta-row">
        <CopyBtn text={bundleMarkdown(data)} label="Copy all fixes" cls="copy-all" />
      </div>

      {scoringCats.map((c) => {
        const checks = byCat.get(c.id) || [];
        return (
          <div key={c.id} id={`cat-${c.id}`} className="cat-block">
            <div className="cat-h">
              <span>{c.label}</span>
              <span className="cat-meta">
                {c.passed}/{c.total} pass
              </span>
            </div>
            {checks.map((f) => {
              if (f.locked && !unlocked) {
                if (!gateRendered) {
                  gateRendered = true;
                  return (
                    <React.Fragment key={f.id}>
                      <Gate locked={lockedCount} scanId={data.scanId} onSent={onSent} />
                      <div className="locked-stack">{`+${lockedCount} more fixes`}</div>
                    </React.Fragment>
                  );
                }
                return null;
              }
              return <FixCard key={f.id} finding={f} url={data.url} density={tweaks.density} />;
            })}
          </div>
        );
      })}

      {/* Commerce + any non-scoring findings render under their own category id
          if present in findings but absent from scoringCats. */}
      {Array.from(byCat.keys())
        .filter((catId) => !scoringCats.some((c) => c.id === catId))
        .map((catId) => {
          const checks = byCat.get(catId) || [];
          const label = checks[0]?.categoryLabel || catId;
          return (
            <div key={catId} id={`cat-${catId}`} className="cat-block">
              <div className="cat-h">
                <span>{label}</span>
                <span className="cat-meta">informational</span>
              </div>
              {checks.map((f) => (
                <FixCard key={f.id} finding={f} url={data.url} density={tweaks.density} />
              ))}
            </div>
          );
        })}

      <TweaksPanel t={tweaks} />
    </div>
  );
}

// ---- root -----------------------------------------------------------------

export function AeoAnalyzer() {
  const [theme, setTheme] = useState<"light" | "dark">(initialTheme);
  const [stage, setStage] = useState<"landing" | "scanning" | "results">("landing");
  const [url, setUrl] = useState("");
  const [data, setData] = useState<ScanResponse | null>(null);
  const [unlocked, setUnlocked] = useState(false);
  const [error, setError] = useState("");
  const [scanDone, setScanDone] = useState(false);
  const tweaks = useTweaks();
  const bootstrapped = useRef(false);
  const runScanRef = useRef<((u: string) => Promise<void>) | null>(null);

  useEffect(() => {
    try {
      localStorage.setItem("aeo-theme", theme);
    } catch {
      /* ignore */
    }
  }, [theme]);

  // On load, restore a scan from ?scan=<id> and unlock if ?unlocked=1 + cookie.
  useEffect(() => {
    if (bootstrapped.current) return;
    bootstrapped.current = true;
    const params = new URLSearchParams(window.location.search);
    const scanId = params.get("scan");
    const wantUnlock = params.get("unlocked") === "1";
    if (params.get("aeo_error")) {
      setError("That confirmation link is invalid or expired. Run the scan again.");
    }
    // Deep-link from marketing pages: /analyzer?url=<site> auto-runs a scan.
    const presetUrl = params.get("url");
    if (!scanId && presetUrl && presetUrl.trim()) {
      void runScanRef.current?.(presetUrl.trim());
      return;
    }
    if (!scanId) return;
    (async () => {
      if (wantUnlock) {
        const full = await apiGetScan(scanId, true);
        if (full) {
          setData(full);
          setUnlocked(true);
          setStage("results");
          return;
        }
      }
      const gated = await apiGetScan(scanId, false);
      if (gated) {
        setData(gated);
        setStage("results");
      }
    })();
  }, []);

  const toggle = useCallback(() => setTheme((t) => (t === "dark" ? "light" : "dark")), []);

  const runScan = useCallback(async (target: string) => {
    setUrl(target);
    setError("");
    setScanDone(false);
    setStage("scanning");
    try {
      const res = await apiScan(target);
      setData(res);
      setScanDone(true);
      // brief beat so the final scan phase is visible, then show results
      setTimeout(() => setStage("results"), 350);
    } catch (e) {
      const msg = e instanceof Error ? e.message : "SCAN_FAILED";
      setError(friendlyError(msg));
      setStage("landing");
    }
  }, []);
  runScanRef.current = runScan;

  return (
    <div className="aeo-root aeo-app" data-theme={theme}>
      <div className="topbar">
        <div className="brand">
          <span className="brand-dot">✦</span>
          <span>AIPUSH · AEO Analyzer</span>
        </div>
        <button className="theme-btn" type="button" onClick={toggle} aria-label="Toggle light/dark theme">
          {theme === "dark" ? "☀" : "☾"}
        </button>
      </div>

      {stage === "landing" && <Landing onAnalyze={runScan} error={error} />}
      {stage === "scanning" && <Scanning url={url} done={scanDone} />}
      {stage === "results" && data && (
        <Results data={data} tweaks={tweaks} unlocked={unlocked} onSent={() => undefined} />
      )}

      {(stage === "results" && (unlocked || data?.locked === false)) && (
        <footer className="site-foot">
          <a href="/privacy">Privacy</a>
          <a href="/terms">Terms</a>
          <span>© AIPUSH</span>
        </footer>
      )}
    </div>
  );
}

function friendlyError(code: string): string {
  switch (code) {
    case "URL_REQUIRED":
      return "Please enter a website URL.";
    case "URL_INVALID":
    case "TARGET_URL_INVALID":
      return "That doesn't look like a valid URL.";
    case "TARGET_URL_NOT_HTTPS":
      return "Only https:// sites can be scanned.";
    case "TARGET_URL_IP_LITERAL":
    case "TARGET_URL_RESOLVES_PRIVATE":
      return "That address can't be scanned.";
    case "TARGET_URL_DNS_FAILED":
      return "We couldn't resolve that domain. Check the URL and try again.";
    default:
      return "We couldn't scan that site. Please try again.";
  }
}

export default AeoAnalyzer;
